{
 "title": "MInu Dashbaord",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\".+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Check Fails",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_health_checks_failed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": {
    "content": "<p align=\"center\">\n  <br>\n  <img src=\"https://i.postimg.cc/T3PchvCB/Moby-logo.png\" height=\"70\" width=\"70\">\n</p>\n"
   }
  },
  {
   "title": "Container States Since Boot",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_actions_seconds_count",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Web App GET Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "container:webapp:requests:total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Container CPU Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}